-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.address
(
    id bigint NOT NULL,
    company_id bigint,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.car
(
    id bigint NOT NULL,
    barter boolean,
    car_about character varying(255) NOT NULL,
    car_showroom boolean,
    credit boolean,
    distance bigint NOT NULL,
    price numeric(19, 2) NOT NULL,
    city_id bigint NOT NULL,
    color_id bigint NOT NULL,
    fuel_id bigint NOT NULL,
    gear_type_id bigint NOT NULL,
    marka_id bigint NOT NULL,
    model_id bigint NOT NULL,
    transmitter_id bigint NOT NULL,
    year_id bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.car_advertisement
(
    id bigint NOT NULL,
    explanation character varying(255),
    release_date date,
    car_id bigint NOT NULL,
    seller_id bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.city
(
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.color
(
    id bigint NOT NULL,
    color_type character varying(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.company
(
    id bigint NOT NULL,
    company_about character varying(255),
    company_name character varying(255),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.customer
(
    id bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.favorite
(
    id bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.fuel
(
    id bigint NOT NULL,
    fuel_type character varying(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.gear_type
(
    id bigint NOT NULL,
    type character varying(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.link
(
    id bigint NOT NULL,
    gmail_link character varying(255),
    linkedin_link character varying(255),
    messenger_link character varying(255),
    whatsapp_link character varying(255),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.marka
(
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.mobile
(
    id bigint NOT NULL,
    "number" bigint,
    company_id bigint,
    seller_id bigint,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.model
(
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    marka_id bigint,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.photo
(
    id bigint NOT NULL,
    url character varying(255) NOT NULL,
    car_id bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.seller
(
    id bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.transmitter
(
    id bigint NOT NULL,
    transmitter_type character varying(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    email character varying(100) NOT NULL,
    password character varying(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.year
(
    id bigint NOT NULL,
    date smallint NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.address
    ADD FOREIGN KEY (company_id)
    REFERENCES public.company (id)
    NOT VALID;


ALTER TABLE public.car
    ADD FOREIGN KEY (marka_id)
    REFERENCES public.marka (id)
    NOT VALID;


ALTER TABLE public.car
    ADD FOREIGN KEY (year_id)
    REFERENCES public.year (id)
    NOT VALID;


ALTER TABLE public.car
    ADD FOREIGN KEY (model_id)
    REFERENCES public.model (id)
    NOT VALID;


ALTER TABLE public.car
    ADD FOREIGN KEY (fuel_id)
    REFERENCES public.fuel (id)
    NOT VALID;


ALTER TABLE public.car
    ADD FOREIGN KEY (city_id)
    REFERENCES public.city (id)
    NOT VALID;


ALTER TABLE public.car
    ADD FOREIGN KEY (color_id)
    REFERENCES public.color (id)
    NOT VALID;


ALTER TABLE public.car
    ADD FOREIGN KEY (transmitter_id)
    REFERENCES public.transmitter (id)
    NOT VALID;


ALTER TABLE public.car
    ADD FOREIGN KEY (gear_type_id)
    REFERENCES public.gear_type (id)
    NOT VALID;


ALTER TABLE public.car_advertisement
    ADD FOREIGN KEY (car_id)
    REFERENCES public.car (id)
    NOT VALID;


ALTER TABLE public.car_advertisement
    ADD FOREIGN KEY (seller_id)
    REFERENCES public.seller (id)
    NOT VALID;


ALTER TABLE public.customer
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.mobile
    ADD FOREIGN KEY (company_id)
    REFERENCES public.company (id)
    NOT VALID;


ALTER TABLE public.mobile
    ADD FOREIGN KEY (seller_id)
    REFERENCES public.seller (id)
    NOT VALID;


ALTER TABLE public.model
    ADD FOREIGN KEY (marka_id)
    REFERENCES public.marka (id)
    NOT VALID;


ALTER TABLE public.photo
    ADD FOREIGN KEY (car_id)
    REFERENCES public.car (id)
    NOT VALID;


ALTER TABLE public.seller
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;

END;